version: '3'

services:
  tool-application:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    container_name: tool_application
    restart: always
    expose:
      - 8080
    depends_on:
      - tool-database
      - tool-redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - /home/suhyang419/images:/app/files