version: '3'

services:
  inkspire:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    container_name: inkspire
    restart: always
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
    volumes:
      - /home/suhyang419/images:/app/files
