spring:
  jackson:
    time-zone: Asia/Seoul
  config:
    import: classpath:/env.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${inkspire.mysql.password}
    url: ${inkspire.mysql.url}
    username: ${inkspire.mysql.username}
  jpa:
    database: sql-server
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
oauth:
  github:
    end-point: ${oauth.github.end-point}
    clientId: ${oauth.github.clientId}
    clientSecret: ${oauth.github.clientSecret}
  google:
    end-point: ${oauth.google.end-point}
    clientId:  ${oauth.google.clientId}
    clientSecret: ${oauth.google.clientSecret}
    scopes: ${oauth.google.scopes}
    access-type: ${oauth.google.access-type}
jwt:
  secret-key: ${jwt.secretKey}
  access-time: ${jwt.access-time}
  refresh-time: ${jwt.refresh-time}
  cookie:
    access-time: ${jwt.cookie.access-time}
    refresh-time: ${jwt.cookie.refresh-time}

